services:
  app:
    build:
      context: ./portfolio-be
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/portfolio # Connect to localhost
      SPRING_DATASOURCE_USERNAME: postgres # Use your PostgreSQL username (e.g., postgres)
    