frontend-deployment:
  url: http://localhost:3000

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/portfolio
    username: postgres
    password: pass
    driverClassName: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    mappings:
      enabled: true
#auth0:
##  clientId: dErtDK4v3hzp0FoM26aX9qGDayGobMIs
##  clientSecret: "hzlT0vFjt6RvkYIT9Y5mZcB6Vl_vAA3McVxf_2yMsmI4E074pQqbGn3G4ZpTxMXI"
#  domain: dev-im24qkb6l7t2yhha.ca.auth0.com
##  audience: https://dev-im24qkb6l7t2yhha.ca.auth0.com/api/v2/
