frontend-deployment:
  url: https://sea-turtle-app-xqswa.ondigitalocean.app

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://db-postgresql-tor1-09928-do-user-18947087-0.d.db.ondigitalocean.com:25060/defaultdb?sslmode=require
    username: doadmin
    password: AVNS_6errXECsD4aWhVYNrAj
    driver-class-name: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    mappings:
      enabled: true

